# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKKOsj54QI7qbUYVRjP5ps-SSL4ReZ0y
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

import warnings
warnings.filterwarnings("ignore")

from google.colab import files

uploaded = files.upload()

train = pd.read_csv("train_c.csv")
val = pd.read_csv("val.csv")
test = pd.read_csv("test_no_label.csv")

print(train.shape)
print(val.shape)
print(test.shape)

train.head()

train.info()

train.describe()

"""###Check Class Values"""

train["Class"].value_counts()

"""### 7 Class types DERMASON, SIRA, SEKER, HOROZ, CALI, BARBUNYA, BOMBAY

### **EDA Part**

### 1: Checking for null values
"""

train.isnull().sum()

test.isnull().sum()

val.isnull().sum()

"""#### Zero Nulls

### 2: Class Distribution
"""

sns.countplot(x=train["Class"])
plt.xticks(rotation=45)
plt.show()

"""### 3: Correlation Matrix"""

plt.figure(figsize=(12,8))

sns.heatmap(
    train.drop(columns=["Class"]).corr(),
    cmap="coolwarm"
)

plt.show()

"""###4: Feature Histograms
####skewness
"""

train.hist(figsize=(15,12))
plt.show()

"""### 5: Boxplots for Outliers"""

for col in train.columns[:-2]:
    plt.figure(figsize=(5,3))
    sns.boxplot(x=train[col])
    plt.title(col)
    plt.show()

"""###6: Remove ID Column"""

train.drop("id", axis=1, inplace=True)
val.drop("id", axis=1, inplace=True)

test_ids = test["id"]

test.drop("id", axis=1, inplace=True)

"""###7:Handle Negative Values"""

numeric_cols = train.select_dtypes(include=np.number).columns

for col in numeric_cols:
    train[col] = train[col].abs()
    val[col] = val[col].abs()
    test[col] = test[col].abs()

"""###8:**Encode** Target Labels"""

encoder = LabelEncoder()

train["Class"] = encoder.fit_transform(train["Class"])
val["Class"] = encoder.transform(val["Class"])

"""###9:**Separate** Features and Labels"""

# 1. Combine the loaded train and val sets to stop data loss
full_data = pd.concat([train, val], ignore_index=True)

# 2. Drop highly correlated physical features to prevent overfitting/noise
cols_to_drop = ["Class", "ConvexArea", "EquivDiameter"]
cols_to_drop = [c for c in cols_to_drop if c in full_data.columns] # Safety check

X = full_data.drop(cols_to_drop, axis=1)
y = full_data["Class"]

# 3. Create a random, non-repeating 80/20 split
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.20,  # 80/20 split
    random_state=42, # 42 ensures the random split is non-repeating across reruns
    stratify=y       # Ensures class proportions remain balanced
)

# 4. Drop the same redundant columns from the final test set so dimensions match later
cols_to_drop_test = [c for c in ["ConvexArea", "EquivDiameter"] if c in test.columns]
test = test.drop(cols_to_drop_test, axis=1)

"""###10:**Feature** Scaling"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_val_scaled = scaler.transform(X_val)

X_test_scaled = scaler.transform(test)

"""###11:Baseline Model

#####A)Random Forest
"""

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train_scaled, y_train)

pred = rf.predict(X_val_scaled)

print("Accuracy:")
print(accuracy_score(y_val, pred))

"""#####B)Classification Report"""

print(classification_report(y_val, pred))

"""#####C)Confusion Matrix"""

cm = confusion_matrix(y_val, pred)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d")
plt.show()

"""###12:Improved Models

######Model 1: Random Forest
"""

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    random_state=42
)

"""#####Model 2: Gradient Boosting"""

gb = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.1,
    random_state=42
)

"""#####Model 3: XGBoost (Recommended)"""

!pip install xgboost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    objective='multi:softmax',
    num_class=7,
    random_state=42
)

"""###TRAIN"""

xgb.fit(X_train_scaled, y_train)

pred = xgb.predict(X_val_scaled)

print(accuracy_score(y_val, pred))

"""###13:Hyperparameter Tuning"""

from sklearn.model_selection import GridSearchCV

# Define stricter parameters with regularization to prevent overfitting
params = {
    "n_estimators": [200, 300],
    "max_depth": [4, 6],           # Shallower trees prevent deep memorization
    "learning_rate": [0.01, 0.1],  # Slower learning forces robust patterns
    "reg_lambda": [1, 10]          # L2 Regularization penalizes extreme weights
}

grid = GridSearchCV(
    XGBClassifier(
        objective='multi:softmax',
        num_class=7,
        random_state=42
    ),
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1 # Uses all CPU cores to speed up the grid search
)

grid.fit(X_train_scaled, y_train)

print("Best Parameters chosen to prevent overfitting:", grid.best_params_)

"""#####Getting Best Model"""

best_model = grid.best_estimator_

"""#####Best Validation set:"""

from sklearn.metrics import accuracy_score, classification_report

# 1. Get Predictions for both Train and Validation (Test) sets
y_train_pred = best_model.predict(X_train_scaled)
y_val_pred = best_model.predict(X_val_scaled)

# 2. Calculate Accuracies
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_val, y_val_pred)
accuracy_diff = train_accuracy - test_accuracy

# 3. Assess Model Fit
def evaluate_model_fit(train_acc, test_acc, threshold=0.04):
    diff = train_acc - test_acc
    if diff > threshold:
        return "Overfitted (Train accuracy is significantly higher than Test accuracy)"
    elif train_acc < 0.70 and test_acc < 0.70:
        return "Underfitted (Both Train and Test accuracies are low)"
    else:
        return "Reasonably Fitted (Good generalization, margins are tight)"

# 4. Print Full Report
print("="*60)
print("             FULL MODEL EVALUATION REPORT")
print("="*60)
print(f"Training Set Accuracy: {train_accuracy:.4f}")
print(f"Test (Val) Accuracy:   {test_accuracy:.4f}")
print(f"Difference:            {accuracy_diff:.4f}")
print("-" * 60)
print(f"Model Fit Status:      {evaluate_model_fit(train_accuracy, test_accuracy)}")
print("="*60)
print("\n--- Detailed Test Set Classification Report ---\n")
print(classification_report(y_val, y_val_pred))

"""#####Classification Report"""

from sklearn.metrics import classification_report

print(classification_report(y_val, pred))

"""#####Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_val, pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""#####Feature Importance"""

importances = best_model.feature_importances_

importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': importances
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

importance_df.head(10)

"""#####Top Features"""

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance_df.head(10),
    x='Importance',
    y='Feature'
)

plt.title("Top 10 Most Important Features")

plt.show()

"""#####Training on all data"""

X_full = pd.concat([X_train, X_val])

y_full = pd.concat([y_train, y_val])

X_full_scaled = scaler.fit_transform(X_full)

X_test_scaled = scaler.transform(test)

"""###15:Train Final Model"""

best_model.fit(
    X_full_scaled,
    y_full
)

"""###16: Predict Competition Test Data"""

test_predictions = best_model.predict(
    X_test_scaled
)



"""###17: Create Submission File"""

submission = pd.DataFrame({
    'id': test_ids,
    'Class': test_predictions
})

"""##### Add Labels back

"""

mapping = {
    0: 'BARBUNYA',
    1: 'BOMBAY',
    2: 'CALI',
    3: 'DERMASON',
    4: 'HOROZ',
    5: 'SEKER',
    6: 'SIRA'
}

submission["Class"] = submission["Class"].map(mapping)

submission.head()

submission.to_csv(
    "submission.csv",
    index=False
)

from google.colab import files

files.download("submission.csv")

"""YOUSSEF ESLAM HUSSEIN | 231000070

YOUSSEF KHALID HASHEM | 231000337

ELHASSAN MAHMOUD      | 231013315

OMAR MOHMED ELSANHOURY| 231000141
"""